FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY calculator.py requirements.txt /app/

ENV RESULTPATH=result/

RUN pip3 install -r requirements.txt

CMD python3 calculator.py
